## Load the Raw Dataset

In [66]:
import pandas as pd
import numpy as np

df = pd.read_csv("../Data/processed/heart_raw.csv")
print(df.shape)
df.head()

(303, 14)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

## Load Raw Data and Assign Column Names

In [54]:
columns = [
    "age","sex","cp","trestbps","chol","fbs","restecg",
    "thalach","exang","oldpeak","slope","ca","thal","target"
]

df = pd.read_csv(
    "../Data/extracted/processed.cleveland.data",
    names=columns,
    sep=",",
    encoding="latin1"
)

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0

## Clean Data: Impute Missing Values and Fix Types

In [55]:
df.replace("?", np.nan, inplace=True)

for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df.fillna(df.median(), inplace=True)

## Feature Engineering: Log Transforms and Binning

In [58]:
# Log transforms (handle skewness)
df["log_chol"] = np.log1p(df["chol"])
df["log_trestbps"] = np.log1p(df["trestbps"])

# Binning (clinical ranges)
df["age_group"] = pd.cut(
    df["age"],
    bins=[0,40,55,70,100],
    labels=[0,1,2,3]
).astype(int)

## Define Features (X) and Target (y)

In [ ]:
X = df.drop("target", axis=1)
y = df["target"]

## Train-Test Split (Feature Selection Path)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_selected, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

## Export "Ultra" Processed Data

In [ ]:
pd.DataFrame(X_train).to_csv("../Data/processed/X_train_ultra.csv", index=False)
pd.DataFrame(X_test).to_csv("../Data/processed/X_test_ultra.csv", index=False)
y_train.to_csv("../Data/processed/y_train_ultra.csv", index=False)
y_test.to_csv("../Data/processed/y_test_ultra.csv", index=False)

print("✅ Ultra preprocessing complete")

✅ Ultra preprocessing complete

## Feature Scaling: Standardization

In [ ]:
X = df.drop("target", axis=1)
y = df["target"]

print(X.shape, y.shape)

(303, 13) (303,)

## Export Standard Scaled Datasets

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

y_train.value_counts(), y_test.value_counts()

(target
 0    131
 1    111
 Name: count, dtype: int64,
 target
 0    33
 1    28
 Name: count, dtype: int64)

In [51]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [52]:
import os

os.makedirs("../Data/processed", exist_ok=True)

pd.DataFrame(X_train_scaled, columns=X.columns).to_csv(
    "../Data/processed/X_train.csv", index=False
)
pd.DataFrame(X_test_scaled, columns=X.columns).to_csv(
    "../Data/processed/X_test.csv", index=False
)
y_train.to_csv("../Data/processed/y_train.csv", index=False)
y_test.to_csv("../Data/processed/y_test.csv", index=False)

print("✅ Preprocessed datasets saved successfully")

✅ Preprocessed datasets saved successfully